### ISSUE TITLE
Update how you handle misspellings

### ISSUE THREAD

**Issue by B3none** [cameronshinn/csgo-queue-bot#23]
Perhaps if a potential command with a Levenshtein threshold more than a particular amount just assume they were going for that command and execute it automatically.

**Comment by cameronshinn** [comment]
I considered this for #17 but I think I want to uphold the philosophy that the bot should do *exactly* what it's told to do. I don't want to put much faith in the Levenshtein distance and leave it to only making suggestions.

One case we'd have to consider is between `mdraft` and `tdraft`. If someone types `q!ydraft` then the Levenshtein distance between those two possible commands is the same. Any instance of `Xdraft` would have to arbitrate between the two commands and select one of them in any instance.
